🍙 Display golden ticket winner
TrueFiEng/devcon-raffle pull request #124
Opened 2022-04-22 11:34 UTC by p-sad

2022-04-25 06:16 UTC, b-tarczynski requested changes

2022-04-25 06:16 UTC, b-tarczynski commented on packages/frontend/src/components/AllBids/SettledBidsList.tsx
> +          <GoldenTicketWinner bidderAddress={goldenTicketWinner?.bidderAddress} />
Right now GoldenTicketWinner is displayed in golden ticket winner and raffle section. Let's remove it from raffle section.

2022-04-25 06:16 UTC, b-tarczynski commented on packages/frontend/src/components/AllBids/SettledBidsList.tsx
> +  )
We can move that logic to `filterBids` function to return separate `goldenTicket` field in `Bids` struct.

2022-04-26 08:45 UTC, mrushkova approved these changes

2022-04-26 08:46 UTC, mrushkova submitted a review, later dismissed

2022-04-26 09:27 UTC, b-tarczynski approved these changes

2022-04-26 09:31 UTC, merged